name: gem5 Test

on:
  push:
    branches: [ xs-dev ]
  pull_request:
    branches: [ xs-dev ]

jobs:
  autotest:
    runs-on: self-hosted
    continue-on-error: false
    name: run script autotest.py
    steps:
      - uses: actions/checkout@v2
      - name: run autotest script
        run: python3 .github/workflows/autotest/script/autotest.py -f .github/workflows/autotest/gem5.cfg
