name: gem5 Test

on:
  push:
    branches: [ xs-dev ]
  pull_request:
    branches: [ xs-dev ]

jobs:
  autotest:
    runs-on: self-hosted
    continue-on-error: false
    name: run script autotest.py
    steps:
      - uses: actions/checkout@v2
      - name: Build DRAMSim
        run: |
          export GEM5_HOME=$(pwd)
          cd ext/dramsim3
          git clone git@github.com:umd-memsys/DRAMSim3.git DRAMsim3
          cd DRAMsim3 && mkdir build
          cd build
          cmake ..
          make -j 48
          cd $GEM5_HOME
      - name: Build GEM5 debug
        run: CC=gcc CXX=g++ scons build/RISCV/gem5.debug --linker=gold -j64
      - name: Memory check
        run: |
          export GEM5_HOME=$(pwd)
          bash util/memory_check/run-xs-with-valgrind.sh
          cd $GEM5_HOME
      - name: Build GEM5 opt
        run: scons build/RISCV/gem5.opt -j 48 --gold-linker
      - name: Run paralel autotest script
        run: python3 .github/workflows/autotest/script/autotest.py -f .github/workflows/autotest/gem5.cfg
